services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sisterphpclient:1.3
    ports:
      - "3000:80"
    volumes:
      - ./public:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

