# Use the official Node.js image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port that the Node.js server will run on
EXPOSE 8000

# Run the server.js file
CMD ["npm", "start"]
